# Generated by Django 2.2.12 on 2020-04-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='field_2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='my_field',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
