# Generated by Django 2.2.12 on 2020-04-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_homepage_another_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="another_field",),
    ]
