# Generated by Django 2.2.12 on 2020-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='another_one',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
